### ISSUE TITLE
Unable to read catalogs from olap4j.properties

### ISSUE THREAD

**Issue by bennychow** [rpbouman/pash#2]
I've got a mondrian4 connection defined in olap4j.properties but pash is not able to find it.  I think pash is only looking in MondrianCatalogHelper.  

pash> use mongoFoodmart;
Error: The Mondrian XML: Mondrian Error:No such catalog: mongoFoodmart (00HSBB08)
Error: The Mondrian XML: Name pentaho_operations_mart is not bound in this Context (00HSBE02)

**Comment by rpbouman** [comment]
pash remains a xml/a tool - not olap4j.
